import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavLayout from "@/common/Navbar/NavLayout";
import { useNavigationVisibility } from "@/hooks/NavCheck";
import { pathsToHide } from "@/hooks/NavPaths";

const Manrope = localFont({
  src: "./fonts/Manrope-VariableFont_wght.ttf",
  variable: "--font-manrope",
  weight: "400 500 600 700 800 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Manrope.variable} antialiased`}
      >
        <NavLayout>{children}</NavLayout>
      </body>
    </html>
  );
}
